# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod properties
mod.version=1.3.2
mod.group=io.github.strikeless
mod.id=adventurers-respawns
mod.name=Adventurers Respawns

# Publishing
publish.modrinth=kdozct3L
publish.curseforge=# Curseforge numeric mod ID
