#
# Game dependency and publishing metadata
#
# Release title for Modrinth and Curseforge
mod.mc_title=26.2.x

# Space-separated compatible versions for publishing
mod.mc_targets=26.2

# Minecraft dependency for fabric.mod.json
mod.mc_dep=~26.2


#
# Fabric API
# See versions at https://fabricmc.net/develop/
#
deps.fabric_api=0.155.2+26.2


#
# External dependencies
#
# See versions in https://modrinth.com/mod/modmenu/versions
deps.modmenu=20.0.0

# Yet Another Config Lib, see versions in https://modrinth.coma/mod/yacl/versions
# Note that this is also a runtime dependency, and the version in fabric.mod.json should also be updated upon a major version change.
deps.yacl=3.9.4+26.2-fabric
