#
# Game dependency and publishing metadata
#
# Release title for Modrinth and Curseforge
mod.mc_title=1.21.4

# Space-separated compatible versions for publishing
mod.mc_targets=1.21.4

# Minecraft dependency for fabric.mod.json
mod.mc_dep=1.21.4


#
# Fabric API
# See versions at https://fabricmc.net/develop/
#
deps.fabric_api=0.119.4+1.21.4


#
# External dependencies
#
# See versions in https://modrinth.com/mod/modmenu/versions
deps.modmenu=13.0.0

# Yet Another Config Lib, see versions in https://modrinth.com/mod/yacl/versions
# Note that this is also a runtime dependency, and the version in fabric.mod.json should also be updated upon a major version change.
deps.yacl=3.8.0+1.21.4-fabric
