#
# Game dependency and publishing metadata
#
# Release title for Modrinth and Curseforge
mod.mc_title=26.3

# Space-separated compatible versions for publishing
mod.mc_targets=26.3

# Minecraft dependency for fabric.mod.json
mod.mc_dep=26.3


#
# Fabric loader and API
# See versions at https://fabricmc.net/develop/
#
deps.fabric_loader=0.19.5
deps.fabric_api=0.160.6+26.3


#
# External dependencies
#
# See versions in https://modrinth.com/mod/modmenu/versions
deps.modmenu=21.0.0-beta.1

# Yet Another Config Lib, see versions in https://modrinth.com/mod/yacl/versions
# Note that this is also a runtime dependency, and the version in fabric.mod.json should also be updated upon a major version change.
deps.yacl=3.9.6+26.3-fabric
